### PR TITLE
IPFS Update: 1.4 Goal - Data Exchange

### LINKED ISSUE #273: IPFS Update Sept-Oct 2022 IPFS 1.4
** Describe the use case**
We are working through an update to the learning goals, names of sections, and where we arrange the content in that section. See the work here: https://miro.com/app/board/uXjVOB6tchQ=/

** Describe the problem**
Update the section(s) of the curriculum & learning Goals

**To Dos**
- [x] Update the Goals on the Learning Objectives page of IPFS Curriculum

- [x] Update sections (name if applicable) & come up with sub-goals

- [x] Move and re-write content (without deleting content) to align to learning goals

- [x] Update [Scope & Sequence](https://www.notion.so/pl-strflt/8e6c3e8aa7a446ecb4a2f6cd55462218?v=43c411da4dbf45838a18716547c50929)

- [ ] Update the [Assessment Qs](https://docs.google.com/document/d/1cpVT7EkcWzKe0Vb1ENk_jeSY1tB6RhVzy0fmXZbvao0/edit?usp=sharing)

- [ ] Update the [Pre & section quizzes](https://drive.google.com/drive/u/0/folders/1VUzXRQaYNIO-nR2j5Kut0nkbHnxgELTs)

**When you work on this issue, start on the branch**:
```
git checkout feat/ipfs-update
git checkout -b <name>/ipfs1.?
```

### PR DESCRIPTION
**Pull request by enoldev**
Fixes #273
After the research on data exchange and Bitswap, I've come up with the following subgoals:

* **1.41 –** Understand that Bitswap is a message-oriented protocol to exchange data.
* **1.42 –** Understand how Bitswap works (message types and flow of the messages)
* **1.43 –** Understand what is _the session_ and _the ledger_ in the context of Bitswap
* **1.44 –** Understand the different components of Bitswap at a high level
* **1.45 –** Understand what is Graphsync and what advantages it involves over Bitswap

### CODE REVIEW

**Comment by mrodriguez3313** [comment]
My final comments are: 
- I personally don't like the aesthetic of the drawings, I don't like that they look penciled in
- The PR is supposed to be merged into [feat/ipfs-update](/protocol/launchpad/tree/feat/ipfs-update) so we can merge everything all together when we are done with this module

**Review by mrodriguez3313 — COMMENTED** [review]
See PR #297 for review and [comments on PR](https://github.com/protocol/launchpad/pull/282#issuecomment-1275287057)

**Comment by enoldev** [comment]
About the drawings, I don't hate them. I think we agreed to use Excalidraw because other DevRel and Docs people were using it

**Comment by walkerlj0** [comment]
I think excalidraw is the way to go, the outercore team/ dev rels are using
this and it's becoming the most widely accepted diagram drawing software
amongst many of the outercore & engineering teams

- Lindsay Walker
https://ovou.me/lindz

**Comment by mrodriguez3313** [comment]
Yes but my follow up question is, what setting are people using it with? Is it with little, mid, or more "sloppiness"? I like the "little sloppiness" line style. I think it looks most professional and that's my only concern.

**Review by mrodriguez3313 — APPROVED** [review]

**Comment by mrodriguez3313** [comment]
Its okay. I say merge it, and we keep an ear out for opinions on it later. I just wanted to express my feelings for it. @enoldev I leave you the honors of merging to feat/ipfs-update branch :thumbsup:

**Pull request merged**
