### PR TITLE
Migration: IPFS section

### PR DESCRIPTION
**Pull request by enolal826**
As part of the Hugo migration, this PR includes the IPFS section.

### CODE REVIEW

**Comment by walkerlj0** [comment]
Content looks great, but two funcitonal bugs I noticed, 
Clicking on the 'Learn' button on the main homepage is a broken link. Note that 'curriculum' is spelled wrong, can you correct it in menu.toml to `/curriculum/?

Functional but- when you click on the curriculum section, all the menus are open (even though the carat icon is pointing left not down) Can we default to a menu where the sections aren't expanded?

Screen Shot 2022-07-27 at 10 56 38 AM

**Review by walkerlj0 — CHANGES_REQUESTED** [review]
See two requests for the functionality

**Comment by enolal826** [comment]
@walkerlj0 I've removed the Learn button for the moment. The idea is to have a completely different landing page. I've changed the menu expansion feature.

**Review by walkerlj0 — APPROVED** [review]
Looks amaze! thanks

**Pull request merged**
